name: Fetch&Push Latest Risk Data

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sync Risk Data
        uses: actions/checkout@v3
        with:
          ref: api
          path: Archive

      - name: Steup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          rm -rf Archive/.git
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch and Save Latest Risk Data
        env:
          FORCE_UPDATE: ${{ secrets.FORCE_UPDATE }}
        run: |
          if python -u risk_zwfw.py; then
            echo "push_required=1" >> $GITHUB_ENV;
            echo "msg=Update at `TZ=Asia/Shanghai date`" >> $GITHUB_ENV;
            echo "Updated risk data successfully.";
          else
            echo "No update required.";
          fi

      - name: Push to api Branch
        if: env.push_required == 1
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: api
          FOLDER: Archive
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: ${{ env.msg }}
